export const Error = {
  NET_ERR: 'Please check your internet connection and try again!',
}
export const Authentication = {
  Login: "Please sign in to your admin account!",
  ForgetPassword: "Forgot Password ?",
  ForgetText:
    " Please enter your registered email address to receive an Link for resetting your password.",
  Verify: "Verify your account",
  VerifyText: "We’ve sent an OTP to admin@ulearn.com",
  VText: "Please enter it below to reset the password.",
  ResendOtp: "Resend OTP in",
  GoBack: "Go back to",
  CreatePassword: "Create new password",
  CreateText: "Please set a new password for your account.",
  CreatePasswordButton: "Set password & Sign in",
  SignIn: "Sign in",
  Submit: "Submit",
};
export const SidebarTitle = {
  Dashboard: "Dashboard",
  UserManagement: "User Management",
  Subscription: "Subscription",
  Blogs: "Blogs",
  Master: "Master",
  Symptoms: "Symptoms",
  HungerOrCravings: "Hunger / Cravings",
  Discharge: "Discharge",
  CycleStage: "Cycle Stages",
  MotivationalQuotes: "Motivational Quotes",
  CMSManagement: "CMS Management",
  TermsAndConditions: "Terms & Conditions",
  PrivacyPolicy: "Privacy Policy",
  AboutUs: "About Us",
  Overview: "Overview",
  Instructions: "Instructions",
  CycleStages: "Cycle Stages",
  ContactUs: "Contact Us",
  FAQs: "FAQ's",
  Logout: "Logout",
};
export const DashboardString = {
  dashBoardTitle: 'Dashboard',
  totalUsersRegistered: 'Total Users Registered',
  totalSubscribedUsers: 'Total Subscribed Users',
  monthlyRevenueGenerated: 'Monthly Revenue Generated',
  activeUsersUsageTrend: 'Active Users Usage Trend',
  monthlyActiveUsersOverview: 'Monthly active users overview',
};
export const UserString = {
  Title: "Users",
  AddButton: "Add User",
  TitleAdd: "Add School",
  filterBy: "Filter by",
  srNo: "Sr No",
  locationName: "location Name",
  adminName: "Admin Name",
  email: "Email",
  viewDetails: "View Details",
  noData: "No Data Found",
  edit: "Edit school",
  delete: "Delete school",
  teachersCount: "Teachers Count",
  joiningDate: "Joining Date",
  UserProfile: "User Profile",
  Activity: "Total Activitys",
  UserName: "User Name",
  location: "Location",
  PhoneNumber: "Phone Number",
  age: "Age",
  language: "Language",
  gender: "Gender",
  occupation: "Occupation"
}
export const UserManagementString = {
  userManagement: "User Management",
  searchUser: "Search User",
  accountStatus: "Account Status",
  filterByDate: "Filter by Registration Date",
  name: "Name",
  email: "Email",
  status: "Status",
  subscription: "Subscription",
  height: "Height",
  weight: "Weight",
  heightInCm: "Height (cm)",
  weightInKg: "Weight (kg)",
  actions: "Actions",
  noUsersFound: "No users found.",
  viewDetails: "View Details",
  userNotFound: "User not found.",
  backToList: "Back to List",
  back: "Back",
  userDetails: "User Details",
  personalInfo: "Personal Information",
  age: "Age",
  physicalMetrics: "Physical Metrics",
  targetWeight: "Target Weight",
  cycleInfo: "Cycle Information",
  cycleLength: "Average Cycle Length",
  duration: "Duration of Period",
  weightLossProgress: "Weight Loss Progress",
  weightLoss: "Actual Weight Loss",
  progressTillDate: "Progress Till Date",
  active: "Active",
  inActive: "Inactive",
  free: "Free",
  weekly: "Weekly",
  monthly: "Monthly",
  yearly: "Yearly",
  years: "years",
  days: "days",
  kg: "kg",
  cm: "cm",
};
export const SubscriptionString = {
  edit: "Edit Plans",
  delete: "Delete Plan",
  deleteConfirmation: "Are you sure you want to delete this subscription plan?",
  free: "Free",
  weekly: "Weekly",
  monthly: "Monthly",
  yearly: "Yearly",
  subscriptionPlan: "Subscription Plans",
  name: "Plan Name",
  type: "Type",
  price: "Price",
  features: "Features",
  validity: "Validity",
  subscribers: "Subscribers",
  actions: "Actions",
  addPlans: "Add Plans",
  editSubscriptionPlans: "Edit Subscription Plan",
  createPlan: "Create New Subscription Plan",
  planType: "Plan Type",
  addFeature: "Add Feature",
  cancel: "Cancel",
  saving: "Saving...",
  saveChanges: "Save Changes",
};
export const BlogString = {
  view: "View Details",
  edit: "Edit",
  delete: "Delete",
  blogs: "Blogs",
  new: "New Blog",
  searchTitle: "Search Title",
  filterByStatus: "Filter By Status",
  title: "Title",
  status: "Status",
  createdAt: "Created At",
  actions: "Actions",
  noBlogsFound: "No blogs found",
  deleteConfirmation: "Are you sure you want to delete?",
  requiredFields: "Please fill in all required fields",
  savingError: "An error occurred while saving. Please try again.",
  back: "Back",
  add: "Add New Blog",
  content: "Content",
  image: "Featured Image",
  saveDraft: "Save Draft",
  publish: "Publish",
  blogNotFound: "Blog not found.",
  backToList: "Back to List",
  details: "Blog Details",
  editBlog: "Edit Blog",
  published: "Published",
  unpublished: "Unpublished",
};
export const cmsString = {
  termsTitle: "Add / Edit Terms and conditions",
  privacyTitle: "Add / Edit Privacy policy",
  overviewTitle: "Add / Edit Overview",
  instructionsTitle: "Add / Edit Instructions",
  cycleStagesTitle: "Add / Edit Cycle Stages",
  aboutUsTitle: "Add / Edit About Us",
  save: "Save details",
};
export const faqString = {
  faq: "FAQ's",
  search: 'Search...',
  question: 'Question',
  answer: 'Answer',
  add: "Add FAQ",
  edit: 'Edit FAQ',
  delete: 'Delete FAQ',
  modalTitle: 'Frequently asked question!',
};
export const defaultOptionsString = {
  search: 'Search...',
  option: 'Option',
  symptom: "Symptoms",
  addSymptom: "Add Symptom",
  editSymptom: 'Edit Symptom',
  deleteSymptom: 'Delete Symptom',
  cycleStages: "Cycle Stages",
  addCycleStage: "Add Cycle Stage",
  editCycleStage: 'Edit Cycle Stage',
  deleteCycleStage: 'Delete Cycle Stage',
  hungerOrCravings: "Hunger / Cravings",
  addHungerOrCraving: "Add Hunger / Craving",
  editHungerOrCraving: 'Edit Hunger / Craving',
  deleteHungerOrCraving: 'Delete Hunger / Craving',
  discharge: "Discharges",
  addDischarge: "Add Discharge",
  editDischarge: 'Edit Discharge',
  deleteDischarge: 'Delete Discharge',
};
export const motivationalQuotesString = {
  motivationalQuotes: "Motivational Quotes",
  search: 'Search...',
  quote: 'Quote',
  import: "Import Motivational Quote",
  add: "Add Motivational Quote",
  edit: 'Edit Motivational Quote',
  delete: 'Delete Motivational Quote',
  modalTitle: 'Motivational Quote',
  file: "Upload File",
};
export const ContactString = {
  title: 'Contact Us',
  searchPlaceholder: 'Search by customer name…',
  viewMessage: 'View message',
  receivedOn: 'Received on',
};
export const CMS_MSG = {
  termsOfService: "Terms and conditions updated successfully!",
  privacyPolicy: "Privacy and policy updated successfully!",
  appSettings: "App settings updated successfully!",
  aboutUs: "About us updated successfully !",
};
export const commonString = {
  phone: "Phone Number",
  email: "Email",
  noDataFound: "No Data Found.",
  saveChanges: "Save Changes",
  name: "Name",
  actions: "Actions",
  filterByDates: "Filter by Dates",
  filterByStatus: "Filter by Status",
  viewAll: "View All",
  noDataAvailable: "No details available for these dates.",
  notSupported: "Your browser does not support the video tag.",
  pleaseWait: "Please wait...",
  cancel: "Cancel",
  appSettings: "App Settings",
  androidVersion: "Android Version",
  iosVersion: "iOS Version",
  androidForce: "Android Force Update",
  iosForce: "iOS Force Update",
  iosMaintain: "iOS App Maintenance",
  androidMaintain: "Android App Maintenance",
  update: "Update",
  deleteCommonText: 'Are you sure you want to remove ',
};